default: &default
  adapter: mysql2
  encoding: utf8
  database: rails_production
  pool: 5
  username: rails_app
  host: localhost

development:
  <<: *default
  password: rails_app

test:
  <<: *default
  password: rails_app

production:
  <<: *default
  password: <%= ENV["DB_PASS"] %>
