default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: mysql2
  encoding: utf8
  database: rails_production
  pool: 5
  username: rails_app
  password: rails_app
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: rails_production
  pool: 5
  username: rails_app
  password: rails_app
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: rails_production
  pool: 5
  username: rails_app
  password: rails_app
  host: localhost
